---

- name: Private Key | Make sure files directory exists.
  ansible.builtin.file:
    path: "{{ acme_cf_files_dir }}/{{ domain }}"
    state: directory
    mode: "755"

- name: Private Key | Generate an OpenSSL RSA 4096 private key for accounts.
  community.crypto.openssl_privatekey:
    path: "{{ acme_cf_files_dir }}/{{ domain }}/{{ domain }}.account.private.key"
    size: 4096
    type: RSA
  register: acme_cf_account_private_key_results

- name: Private Key | Debug out the generated account key.
  ansible.builtin.debug:
    msg: "The private key for Letsencrypt account is generated at {{ acme_cf_account_private_key_results.filename }}."
  tags: [debug]

# Generate private key for CSRs.

- name: Private Key | Generate an OpenSSL RSA 4096 private key for CSRs.
  community.crypto.openssl_privatekey:
    path: "{{ acme_cf_files_dir }}/{{ domain }}/{{ domain }}.private.key"
    size: 4096
    type: RSA
  register: acme_cf_csr_private_key_results

- name: Private Key | Debug out the generated CSR private key.
  ansible.builtin.debug:
    msg:
      - "The private key for the CSR is generated at {{ acme_cf_csr_private_key_results.filename }}."
  tags: [debug]
