---

- name: CSR | Generate the CSRs.
  community.crypto.openssl_csr:
    path: "{{ acme_cf_files_dir }}/{{ domain }}/{{ domain }}.csr"
    privatekey_path: "{{ acme_cf_files_dir }}/{{ domain }}/{{ domain }}.private.key"
    common_name: "*.{{ domain }}"
    email_address: "{{ acme_cf_account_email }}"
    subject_alt_name: |
      {{
      [domain, '*.' + domain]
      | map('regex_replace', '^', 'DNS:')
      | list
      }}
  register: acme_cf_csr_generate_result

- name: CSR | Debug out the generated CSR.
  ansible.builtin.debug:
    msg:
      - "The CSR is generated at {{ acme_cf_csr_generate_result.filename }}."
  tags: [debug]
