---

- name: DNS Challenge | Create a challenge for the wildcard domain.
  community.crypto.acme_certificate:
    account_key_src: "{{ acme_cf_files_dir }}/{{ domain }}/{{ domain }}.account.private.key"
    account_email: "{{ acme_cf_account_email }}"
    csr: "{{ acme_cf_files_dir }}/{{ domain }}/{{ domain }}.csr"
    cert: "{{ acme_cf_files_dir }}/{{ domain }}/{{ domain }}.crt"
    challenge: "dns-01"
    acme_directory: "{{ acme_cf_server_dir }}"
    remaining_days: "{{ acme_cf_remaining_days }}"
    acme_version: 2
    terms_agreed: true
    modify_account: true
  register: acme_cf_dns_challenge_results

- name: DNS Challenge | Debug dns_challenge variable.
  ansible.builtin.debug:
    var: acme_cf_dns_challenge_results
  tags: [debug]

- name: DNS Challenge | Construct new lists for DNS-01 challenge.
  vars:
    __challenge_results: "{{ acme_cf_dns_challenge_results }}"
  ansible.builtin.set_fact:
    __challenge_data: "{{ __challenge_results.challenge_data | default('') }}"
    __domain_txt_value: "{{ __challenge_results.challenge_data[domain]['dns-01'].resource_value | default('') }}"
    __domain_wildcard: "{{ '*.' + domain }}"
    __domain_wildcard_txt_value: "{{ __challenge_results.challenge_data['*.' + domain]['dns-01'].resource_value | default('') }}"

- name: DNS Challenge | Debug out the constructed list.
  ansible.builtin.debug:
    msg:
      - "__challenge_data: {{ __challenge_data }}"
      - "__domain_txt_value: {{ __domain_txt_value }}"
      - "__domain_wildcard: {{ __domain_wildcard }}"
      - "__domain_wildcard_txt_value: {{ __domain_wildcard_txt_value }}"
  tags: [debug]
