---

- name: Generate PKCS#12 certificate.
  community.crypto.openssl_pkcs12:
    action: export
    path: "{{ acme_cf_files_dir }}/{{ domain }}/{{ domain }}.p12"
    friendly_name: "{{ domain }}"
    privatekey_path: "{{ acme_cf_files_dir }}/{{ domain }}/{{ domain }}.private.key"
    certificate_path: "{{ acme_cf_files_dir }}/{{ domain }}/{{ domain }}.fullchain.crt"
    state: present

- name: Debug the PKCS#12 certificate file location.
  ansible.builtin.debug:
    msg:
      - "Cert file: {{ acme_cf_files_dir }}/{{ domain }}/{{ domain }}.p12"
      - "Fullchain cert file: {{ acme_cf_files_dir }}/{{ domain }}/{{ domain }}.fullchain.crt"
  tags: [debug]
