---

- name: Debug certificate files location.
  ansible.builtin.debug:
    msg:
      - "Private key file: {{ acme_cf_files_dir }}/{{ domain }}/{{ domain }}.private.key"
      - "CSR file: {{ acme_cf_files_dir }}/{{ domain }}/{{ domain }}.csr."
      - "Cert file (.crt): {{ acme_cf_files_dir }}/{{ domain }}/{{ domain }}.crt."
      - "Cert file (.p12): {{ acme_cf_files_dir }}/{{ domain }}/{{ domain }}.p12."
      - "Intermediate file: {{ acme_cf_files_dir }}/{{ domain }}/{{ domain }}.intermediate.crt."
      - "Fullchain cert file: {{ acme_cf_files_dir }}/{{ domain }}/{{ domain }}.fullchain.crt."
  tags: [debug]
